version: '3.8'

services:
  # Database Service
  database:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eventsProject                
    ports:
      - "3306:3306"  # Expose MySQL on port 3306 to the host machine

  # Spring Boot Application Service
  app:
    image: fatmaezzine/backend:latest    # Replace with your actual Spring Boot app image
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root    
      SPRING_DATASOURCE_PASSWORD: 1234       
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    ports:
      - "8089:8089"  # Expose Spring Boot app on port 8089 to the host machine
    depends_on:
      - database      # Ensure the database starts before the app