version: '3.8'

services:
  # Database Service
  database:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: eventsProject  
      MYSQL_USER: root                 
      MYSQL_PASSWORD: ""               
    ports:
      - "3306:3306"                     


  # Spring Boot Application Service
  app:
    image: fatmaezzine/backend:latest    
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/eventsProject?
      SPRING_DATASOURCE_USERNAME: root    
      SPRING_DATASOURCE_PASSWORD:        
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
    ports:
      - "8089:8089"                      
    depends_on:
      - database 